name: Example workflow for S3 Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - name: Checkout repository
          run: git clone --recurse-submodules https://github.com/caiocsgomes/caiogomes.me.git

        - name: Listing folders
          run: ls -lha

        - name: Install hugo
          run: sudo apt install hugo

        - name: Build
          run: cd caiogomes.me/app/ && hugo

        - name: Install aws cli
          id: install-aws-cli
          uses: unfor19/install-aws-cli-action@v1
          with:
            version: 2
            verbose: false
            arch: amd64
            rootdir: ""
            workdir: "" 

        - name: Set AWS credentials
          run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} && export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: Upload files to S3
          run: aws s3 sync caiogomes.me/app/public/ s3://caiogomes.me/ --recursive
