name: Example workflow for S3 Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - name: Checkout repository
          run: git clone --recurse-submodules https://github.com/caiocsgomes/caiogomes.me.git

        - name: Listing folders
          run: ls -lha

        - name: Install hugo
          run: sudo apt install hugo

        - name: Build
          run: cd caiogomes.me/app/ && hugo

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: "caiogomes.me/app/public/*"